intel/rohd-hcl

lib/src/one_hot.dart
test/one_hot_test.dart

Cleanup implementation and test of one-hot codec
Resolves issue #3
Removed OrReduction class and tests.  Replaced with .or() bitlevel function.
Nothing should be using the OrReduction class.
No update

use built-in or-reduction

---

.github/workflows/general.yml
README.md
doc/memory.md
lib/rohd_hcl.dart
lib/src/memory.dart
test/rf_test.dart

Documentation for memory and register files
N/A
N/A
YES!  Renamed `PortGroup` to `DataPortGroup`.  Not enough consumers so far (not even released yet), so this should be ok for now.
No

Add documentation for memory and register files

---

doc/fifo.md
lib/src/fifo.dart
test/fifo_test.dart

Sometimes the bypass in the FIFO is not needed, and so some logic can be removed.
Additionally, it appears that yosys formal tools may have some bugs in combinational loop detection which an unused bypass can potentially expose.
This PR adds `generateBypass` as an argument for the `Fifo`, with a default of `false`.
N/A
Added tests for peeking with and without bypass, and updated bypass test to enable bypass generation.
Yes!  Bypass is now _not_ generated by default.
Updated the FIFO docs

Make FIFO bypass generation optional

---

README.md
doc/arbiter.md

Adding documentation for `Arbiter` and `PriorityArbiter`, plus link from README.
N/A
N/A
No
That's all it is

Add documentation for arbiters

---

README.md
doc/standard_interfaces.md
lib/rohd_hcl.dart
lib/src/interfaces/apb.dart
lib/src/interfaces/interfaces.dart
test/apb_test.dart

Add a configurable implementation of the APB interface to ROHD-HCL using ROHD `Interface`s, including docs.
N/A
Added some tests that it can be instantiated, used, and optional ports can be null.
No
Yes, new doc and updated README

Add the APB standard interface

---

.github/workflows/general.yml
.gitmodules
.markdownlint-cli2.jsonc
build/README.md
doc/arbiter.md
doc/fifo.md
doc/memory.md
doc/onehot.md
doc/rotate.md
gen/arbiter_gen.dart
gen/fifo_gen.dart
gen/generate.dart
gen/one_hot_gen.dart
gen/rf_gen.dart
gen/rotate_gen.dart
test/one_hot_test.dart
tool/converters/json_html.sh
tool/converters/verilog_html.sh
tool/converters/verilog_json.sh
tool/gh_actions/create_htmls.sh
tool/gh_actions/generate_documentation.sh
tool/gh_actions/install_d3_hwschematic.sh
tool/gh_actions/install_opencadsuite.sh
tool/gh_actions/install_schematic.sh
tool/gh_codespaces/run_setup.sh
tool/synthesize.sh

This code generates interactive HTML schematics for components.  The current documentation points to the generated HTML.  
All known issues from the previous pull request were fixed (sync writes, separate generation, binary for yosys, submodule for d3-hwschematic).
This code uses the d3-hwschematic code to generate HTML for viewing schematics. A custom script injects JSON for the circuit into a single HTML file per schematic to avoid file loading.  The JSON is produced from Yosys.
Resolves issue #23 
By testing in a fork, I have verified that documentation linkage will work.
We will need to reset links in the documentation to point to the production deployment area.
> Does the change require any updates to …

Schematic Generation

---

.github/workflows/general.yml
doc/fifo.md
doc/standard_interfaces.md
tool/gh_codespaces/run_setup.sh

The dev container broke, and it's because we weren't testing it.  This tests it.
(Also, fix some typos in docs)
N/A
CI will test
No
N/A

Add testing for dev container in CI, and doc tweaks

---

lib/src/fifo.dart

There was some extra logic getting generated when bypass generation was disabled in the FIFO.  This fixes that.
N/A
Existing tests cover it
No
No

Remove extra bypass logic when bypass is not generated in FIFO

---

doc/fifo.md
lib/src/fifo.dart
pubspec.yaml
test/fifo_test.dart

Adds a ROHD-VF `FifoChecker` and `FifoTracker` that can be used to validate proper usage of the `Fifo` in designs.
Also, refactored `Fifo` a little and removed a few unnecessary gates depending on configuration.
N/A
Added new tests
No
Yes, updated docs

Checking and tracking for `Fifo`

---

.github/workflows/general.yml

Updating to use a new type of self-hosted runner for GitHub actions. This should help with the slow pick-up of jobs from the GitHub-hosted runners.
N/A
This is it!
No
No

Update to use new runners in github actions

---

lib/src/fifo.dart
test/fifo_test.dart

When the FIFO was configured to depth=1, the computed address width was 0, which violated some assumptions in the design.  In the future, there may be room for optimization to account for when the address is unnecessary, but those changes are not included in this PR.
N/A
Added a new test and an assertion.  New version of ROHD will hit errors.
No
No

Fix bug where FIFO depth 1 generated 0-width address

---

.github/workflows/general.yml

Both of the pages deployments had `clean: true` (implicitly), which meant whichever ran second would delete whichever ran first.  This PR orders them, and prevents the second from doing a "clean".
N/A
This is it!
No
No

Fix generation of website with confapp

---

.github/workflows/general.yml
.pubignore
doc/components/arbiter.md
lib/rohd_hcl.dart
lib/src/arbiters/arbiter.dart
lib/src/arbiters/arbiters.dart
lib/src/arbiters/mask_round_robin_arbiter.dart
lib/src/arbiters/priority_arbiter.dart
lib/src/arbiters/rotate_round_robin_arbiter.dart
lib/src/arbiters/round_robin_arbiter.dart
lib/src/arbiters/stateful_arbiter.dart
lib/src/component_config/components/component_registry.dart
lib/src/component_config/components/components.dart
lib/src/component_config/components/config_rotate.dart
lib/src/component_config/components/config_round_robin_arbiter.dart
test/arbiter_test.dart

This PR primarily adds a second implementation of a RoundRobinArbiter.  It also includes:
- Fix a bug where RoundRobinArbiter would reset state incorrectly when no grants are given (and adds a test for this)
- Reorganizes arbiter inheritance structure to support more arbiter types more easily
N/A
Added a new test and organized tests to test all round-robin arbiters the same way
No
No

Round robin arbiters updates

---

build/README.md
gen/generate.dart
lib/src/arbiters/mask_round_robin_arbiter.dart
tool/gh_actions/create_htmls.sh
tool/gh_actions/install_opencadsuite.sh
tool/gh_codespaces/run_setup.sh

A recent change broke the schematic generation (the name of the module was wrong in the script).  This PR fixes that.
N/A
Ran in codespace
No
No

Fix schematic generation and links

---

.gitignore
doc/README.md
doc/components/apb_bfm.md
doc/components/ready_valid_bfm.md
lib/src/models/models.dart
lib/src/models/ready_valid_bfm/ready_valid_agent.dart
lib/src/models/ready_valid_bfm/ready_valid_bfm.dart
lib/src/models/ready_valid_bfm/ready_valid_monitor.dart
lib/src/models/ready_valid_bfm/ready_valid_packet.dart
lib/src/models/ready_valid_bfm/ready_valid_receiver_agent.dart
lib/src/models/ready_valid_bfm/ready_valid_tracker.dart
lib/src/models/ready_valid_bfm/ready_valid_transmitter_agent.dart
lib/src/models/ready_valid_bfm/ready_valid_transmitter_driver.dart
test/ready_valid_bfm_test.dart

An implementation of a Ready/Valid BFM.
N/A
Includes testing.
No
Yes, added new doc

Ready/Valid BFM

---

lib/src/fifo.dart
test/fifo_test.dart

There were some bugs in the way the `FifoChecker` sampled signals at clock edges, causing false failures.  This PR fixes those.
N/A
Added a new test that catches these issues, confirmed fix fixes them.
No
No

Fix `FifoChecker` sampling bugs

---

doc/README.md
lib/src/memory/memory.dart
lib/src/models/apb_bfm/apb_tracker.dart
lib/src/models/memory_model.dart
pubspec.yaml
test/arbiter_test.dart
test/fifo_test.dart
test/memory_test.dart
test/shift_register_test.dart

This PR:
- Fix bugs related to memory model sampling on negative edges and improper handling of zero-latency accesses.
- Fix error handling and assertions in constructing `Memory` (e.g. bug where assertion fired incorrectly)
- Updates doc/README with more components
- Update APB tracker to have configurable widths for addr and data
N/A
Added new tests
No
No

Fix memory model handling of different edge and latency situations

---

lib/src/models/memory_model.dart
test/memory_test.dart

This PR fixes some more bugs related to the memory model and adds more tests to catch the issues.  Mainly:
- A read immediately following a write with zero-latency could result in old data being returned.
- A read on non-zero-latency could sometimes return data for a new address instead of the posedge sampled address.
N/A
Added a bunch of new testing
No
No

More fixes to the memory model

---

doc/README.md
doc/components/edge_detector.md
lib/rohd_hcl.dart
lib/src/component_config/components/component_registry.dart
lib/src/component_config/components/components.dart
lib/src/component_config/components/config_edge_detector.dart
lib/src/count.dart
lib/src/edge_detector.dart
test/arbiter_test.dart
test/edge_detector_test.dart
test/fifo_test.dart
test/memory_test.dart

Adds a configurable edge detector.  Also a little bit of misc cleanup.
N/A
Added new tests.
No
Yes, added docs

Edge Detector

---

doc/components/parallel_prefix_operations.md
lib/rohd_hcl.dart
lib/src/component_config/components/component_registry.dart
lib/src/component_config/components/components.dart
lib/src/component_config/components/config_parallel_prefix_adder.dart
lib/src/parallel_prefix_operations.dart
pubspec.yaml
test/configurator_test.dart
test/parallel_prefix_operations_test.dart

Parallel prefix trees implementing adders, priorityencoder, incrementer, decrementer, and orscan
#12 
Tests included for each component with each flavor of prefix tree.
No.
Yes.  The new components have updated documentation, and an attempt at making the configurator work with the adder.

migrate parallel_prefix to new branch

---

lib/src/component_config/components/component_registry.dart
lib/src/component_config/components/components.dart
lib/src/component_config/components/config_edge_detector.dart
lib/src/component_config/components/config_find.dart
test/configurator_test.dart

The `Find` was not available as a configurator or in the web-app, so this adds it.
Also, small bug fix in the edge detector configurator where it didn't use the type.
N/A
Added sanity test
No
No

`Find` Configurator

---

confapp/lib/hcl/view/screen/content_widget.dart
confapp/lib/hcl/view/screen/sidebar_widget.dart
confapp/pubspec.yaml
doc/README.md
doc/components/parallel_prefix_operations.md
lib/src/component_config/components/config_parallel_prefix_adder.dart
lib/src/parallel_prefix_operations.dart

This PR updates parallel prefix documentation and links to classes that were not possible on first check-in.
During CI: discovered problem with google-fonts where the BKM is to lock it to a recent but not latest version:
https://stackoverflow.com/questions/78090711/error-type-fontfeature-not-found-flutter-google-fonts-package-error
During CI: discovered a problem with flutter code shadowing arguments of a parent class triggering an error entitled use_super_parameters:
https://dart.dev/tools/linter-rules/use_super_parameters
None
I've tested the documentation links in my fork.   I've also added a linear adder test for narrow adders to complement the random test.
No
> Does the change require any updates to …

parallel prefix documentation updates

---

confapp/lib/hcl/cubit/system_verilog_cubit.dart
confapp/lib/hcl/view/screen/content_widget.dart
confapp/lib/hcl/view/screen/d3Schematic.dart
confapp/lib/hcl/view/screen/schematic.dart
confapp/web/yosysWorker.js

Enable a web-based schematic generation capability using yoWASP and d3schematics
None
Ran the flutter confapp application locally.
No.
No documentation needed as this is a change to the generator app visible to the end user.

schematic only changes

---

.pubignore
README.md
doc/README.md
test/configurator_test.dart

Since we have a component registry, we may as well try building all of them to ensure there's no issue with the configurators.
This PR also includes a couple minor updates:
- link to the ROHD website on README
- update .pubignore to ignore some files already in .gitignore
- fix links for gray stuff in component list
N/A
Just added a test
No
No

Add tests that configurator modules build

---

doc/components/shift_register.md
lib/src/shift_register.dart
test/shift_register_test.dart

The shift register component was changed to include functionality for asynchronous reset and for individual stages of the shift register to have different reset values. 
Motivation stems from a need for this functionality in implementing SPI for ROHD.
N/A
More tests were added to the existing shift register tests, testing lists of reset values and async reset.
No
Component documentation was updated

Shift Register Updates

---

doc/components/divider.md
lib/src/arithmetic/divider.dart
test/arithmetic/divider_test.dart

Adding a remainder output so that this unit can be used for implementing the modulo operator. Adding an isSigned input so that the unit can handle unsigned operands if the integrating environment wants this.
N/A
Enhanced existing testbench/checker to test the remainder output and mix in the use of the isSigned input.
No breaking changes.
Documentation has been updated accordingly.

Multi Cycle Divider Enhancements: remainder output and isSigned input

---

doc/components/fixed_point.md
lib/src/arithmetic/arithmetic.dart
lib/src/arithmetic/float_to_fixed.dart
lib/src/component_config/components/component_registry.dart
lib/src/component_config/components/components.dart
lib/src/component_config/components/config_float8_to_fixed.dart
lib/src/component_config/components/config_float_to_fixed.dart
test/arithmetic/float_to_fixed_test.dart

- `FloatToFixed` is a new component for lossless conversion of a floating-point type to a fixed-point type.
- `Float8ToFixed` is a new component for lossless conversion of a FP8 formats to a fixed-point type.
Both components are tested exhaustively.
This PR is not a breaking change.
Both components are added to the documentation.

Floating Point to Fixed Point Converter Module

---

lib/src/arithmetic/floating_point/floating_point_values/floating_point_8_value.dart

ofInt() and ofBigInt() code was incomplete.
None.  We have parallel tests for other operand types, just not this one.  Will open an issue to create more smoke tests.
No.
This is a bug fix.

bug fix for fp8e4m3

---

confapp/README.md
doc/components/multiplier.md
lib/src/arithmetic/multiplicand_selector.dart
lib/src/arithmetic/multiplier.dart
lib/src/arithmetic/partial_product_generator.dart
lib/src/arithmetic/partial_product_sign_extend.dart
lib/src/component_config/components/config_compression_tree_multiplier.dart
test/arithmetic/addend_compressor_test.dart
test/arithmetic/multiplier_encoder_test.dart
test/arithmetic/multiplier_test.dart

Fixed a bug in sign extension that was causing signed operand mode of multiplier to fail (if first operand was signed).
None
Both exhaustive and random testing including ALL sign extension modes, across all radixes and prefix tree types, signed, unsigned, both fixed and logically selected, across critical width transitions, as well as for the multiply-accumulate and pure multiply.
Simple pipeline testing added to make sure timing is correct.
No, but new parameters with defaults extend the multiplier to expose sign selection types and pipelining.
Changes to the operation in the code comments and in the documentation. …

fix signed operand mode in multiplier, added pipelining

---

doc/components/divider.md
lib/src/arithmetic/divider.dart
test/arithmetic/divider_test.dart

The MultiCycleDivider has the following bugs:
(1) Polarity of the readyIn output is flipped relative to what it should be.
(2) Unsigned cases of division involving very large operands (MSB=1) do not produce correct results and can even deadlock the unit.
This PR fixes these and adds tests for the exceptional cases moving forward. 
N/A
Added a new sequence for "evil" cases of division stressing large operands in both signed and unsigned. Fixed a bug in the testbench preventing testing of readyIn signal.
This change is backward compatible as the interface to the divider has not changed at all. Only the outputs for a given set of inputs have changed in certain cases.
> Does the change require any updates to …

[MultiCycleDivider] Bug Fixes for Large Operands and Ready Indication Polarity

---

doc/components/multiplier.md
doc/components/multiplier_components.md
lib/src/arithmetic/carry_save_mutiplier.dart
lib/src/arithmetic/evaluate_partial_product.dart
lib/src/arithmetic/multiplicand_selector.dart
lib/src/arithmetic/multiplier.dart
lib/src/arithmetic/multiplier_encoder.dart
lib/src/arithmetic/partial_product_generator.dart
lib/src/arithmetic/partial_product_sign_extend.dart
lib/src/component_config/components/config_carry_save_multiplier.dart
lib/src/component_config/components/config_compression_tree_multiplier.dart
lib/src/utils.dart
test/arithmetic/addend_compressor_test.dart
test/arithmetic/carry_save_multiplier_test.dart
test/arithmetic/multiplier_encoder_test.dart
test/arithmetic/multiplier_test.dart
test/configurator_test.dart

This updates the compression tree mulitplication components to fully handle variations in sign for multiplicand and multiplier.
This includes separate fixed signs for both, as well as a select signal for both and all valid combinations.  When select is enabled for an operand, the fixed sign input parameter is false..
The core parameters are:
- signedMultiplicand
- signedMultiplier
- selectSignedMultiplicand
- selectSignedMultiplier
These parameters are enabled for the CompressionTreeMultiplier and CompressionTreeMultiplyAccumulate.
Major cleanup of the testing routines to ensure solid coverage and reduce testing time.
#143 
Sweep testing of the PartialProductGenerators for all combinations of signed/selected operands and all sign extension methods, across all radix settings.
> Is this a …

Full set of sign variants (signed/unsigned/selected) for multiplier operands

---

lib/src/arithmetic/floating_point/floating_point_adder_round.dart

A redundant assignment statement in the FP adder was caught by more checks in the baseline ROHD code.
None.
Ran the suite of FP regressions.
No.
No change in behavior or API.

remove redundant assignment statement in fpadder

---

doc/README.md
doc/components/adder.md
doc/components/fixed_point.md
doc/components/floating_point.md
doc/components/multiplier.md
doc/components/multiplier_components.md
lib/src/arithmetic/adder.dart
lib/src/arithmetic/carry_save_mutiplier.dart
lib/src/arithmetic/compound_adder.dart
lib/src/arithmetic/floating_point/floating_point_adder_round.dart
lib/src/arithmetic/floating_point/floating_point_adder_simple.dart
lib/src/arithmetic/ones_complement_adder.dart
lib/src/arithmetic/parallel_prefix_operations.dart
lib/src/arithmetic/ripple_carry_adder.dart
lib/src/arithmetic/sign_magnitude_adder.dart
lib/src/component_config/components/config_floating_point_adder_round.dart
lib/src/component_config/components/config_parallel_prefix_adder.dart
lib/src/component_config/components/config_ripple_carry_adder.dart
pubspec.yaml
test/arithmetic/adder_test.dart
test/arithmetic/carry_save_multiplier_test.dart
test/arithmetic/compound_adder_test.dart

Converted all adders to use the same base Adder class with a conditional carry input (Logic? carryIn).
None
Most adders are now tested uniformly in the adder_test.dart file using both carry and non-carry configurations.
Yes.  The FullAdder no longer has a carryOut, it is in sum[1].  Otherwise, other adders now have an optional carryIn.
Yes.  All adder documentation has been updated to reflect the change.

adder api and documentation cleanup

---

confapp/pubspec.yaml
example/clock_gating_example.dart
lib/src/arithmetic/carry_save_mutiplier.dart
lib/src/arithmetic/sign_magnitude_adder.dart
lib/src/clock_gating.dart
lib/src/count.dart
lib/src/find.dart
pubspec.yaml
test/clock_gating_test.dart
test/count_test.dart
tool/gh_actions/generate_documentation.sh

- Adds compatibility with ROHD v0.6.0 and ROHD-VF v0.6.0
- Some minor documentation updates
- Fixed the `Count` module's output API and width calculation
N/A
Existing tests, plus a new one for count
Yes!
Minimum ROHD and ROHD-VF versions are now 0.6.0
No

Compatibility with ROHD v0.6.0, plus some minor fixes

---

.github/workflows/general.yml
confapp/test/hcl/view/hcl_page_test.dart

Bypass link checking and expect problem in flutter test until we can get installation back.
To allow for document install to proceed.
No.

bypass link check and flutter bug for now

---

lib/src/arithmetic/floating_point/floating_point_adder_round.dart
lib/src/arithmetic/floating_point/floating_point_converter.dart
lib/src/arithmetic/signals/fixed_point_logic.dart
lib/src/arithmetic/values/floating_point_values/floating_point_value.dart
test/arithmetic/floating_point/floating_point_adder_round_test.dart
test/arithmetic/floating_point/floating_point_multiplier_test.dart
test/arithmetic/floating_point/floating_point_value_test.dart

Missed adding code to FPAdderRound to check for infinity after adding.
Fixed FloatingPointValue to properly check for infinity in the rounding case.
Existing FP round tests now pass (they were passing before, but FPV and the same bug as FPAdderRound).
No
No change required.

rounding and fixed point fixes

---

doc/components/fixed_point.md
lib/src/arithmetic/fixed_to_float.dart
lib/src/arithmetic/float_to_fixed.dart
lib/src/arithmetic/signals/fixed_point_logic.dart
lib/src/arithmetic/values/fixed_point_value.dart
test/arithmetic/fixed_to_float_test.dart
test/arithmetic/float_to_fixed_test.dart
test/arithmetic/values/fixed_point_value_test.dart

We need converters from float to fixed that are lossy (e.g. are constrained by fixed parameters m, n.  This PR creates this.
Exhaustive testing at narrow widths, e.g., BF16->18.16.
No.
Yes.  Markdown updated to document the addition of optional inputs m,n and the checkOverflow flag.

Fixed lossy

---

lib/src/arithmetic/floating_point/floating_point.dart
lib/src/arithmetic/floating_point/floating_point_adder.dart
lib/src/arithmetic/floating_point/floating_point_adder_round.dart
lib/src/arithmetic/floating_point/floating_point_adder_simple.dart
lib/src/arithmetic/floating_point/floating_point_multiplier.dart
lib/src/arithmetic/floating_point/floating_point_multiplier_simple.dart
lib/src/arithmetic/floating_point/floating_point_utilities.dart
lib/src/arithmetic/signals/floating_point_logics/floating_point_logic.dart

The `swap` and `sort` routines for `FloatingPoint` signals are useful beyond just inside of ROHD-HCL `FloatingPointAdder`s, so this PR extracts them as static functions to a separate `FloatingPointUtilities` class.
Additionally, add some parameterization on inputs for floating point adders and multipliers.  Held off on parameterization of the outputs, since that could cause some backwards incompatible problems when we upgrade so that outputs can be different types than the inputs (as is already the case for multipliers).
N/A
Existing tests should cover, this is not a functional change
No
No

`FloatingPointUtilities` extraction for `swap`/`sort`, and parameterization of some FP components

---

doc/README.md
doc/components/find.md
doc/components/find_pattern.md
lib/rohd_hcl.dart
lib/src/find_pattern.dart
test/find_pattern_test.dart

Similar to Find N'th bit from start/end, but FindPattern find an entire multi-bit pattern from start/end and returns it index
https://github.com/intel/rohd-hcl/issues/169 
Test is included in test/find_pattern_test.dart 
No
Documentation added in doc/components/find.md

Add Find N'th Pattern component

---

lib/src/models/sparse_memory_storage.dart
test/sparse_memory_storage_test.dart

There was a bug in the `SparseMemoryStorage` where data in the first word would get shifted over by one byte (and some other stuff) if you load memory with `loadMemString` twice on overlapping or the same data ranges.  This PR fixes the bug and includes tests to cover the problem.
N/A
Added new tests
No
N/A

Fix bug in `SparseMemoryStorage` where reloading the same data corrupted the first byte

---

test/arithmetic/divider_test.dart

Dart 3.8 introduced a new lint issue.  This PR fixes it.
N/A
This PR will check all is clean.
No
No

Fix lint issues for Dart 3.8

---

doc/components/reduction_tree.md
lib/rohd_hcl.dart
lib/src/reduction_tree.dart
lib/src/reduction_tree_generator.dart
test/reduction_tree_generator_test.dart
test/reduction_tree_test.dart

There are situations where we need control at each level of reduction.
None.
We provide a muxing example that tests that mux input selects come out on the correct cycle.
None.
Yes.  The markdown is updated as is the API documentation for using the new control input.

reduction with control working

---

confapp/lib/hcl/view/screen/sidebar_widget.dart

The generator app displays names incorrectly in the sidebar to the point they are unreadable.
This only happens on wider names where some kind of highlighting or font change happens when wrapping.
Fix #128 
Running flutter locally and attaching to web generator app.
No
No change needed.

Widen the confapp sidebar to allow for names to be displayed properly

---

lib/src/models/axi4_bfm/axi4_main_write_driver.dart
lib/src/models/axi4_bfm/axi4_subordinate.dart

If a main sends a write on a particular channel/address and then in the cycle after WLAST for the write data sends a read on the same channel/address, the subordinate would return the old data instead of the new data.
N/A
Added a unit test for this case.
This change is fully backwards compatible.
No doc updates needed.

AXI4 Subordinate BFM bug fix for tight consecutive write/read

---

doc/components/memory.md
doc/components/onehot.md

Broken html links because we changed generator parameters.
None
Need to test in deployment
No.
This is a doc change.

updated broken html links in markdown

---

example/clock_gating_example.dart
lib/src/arithmetic/divider.dart
lib/src/clock_gating.dart
lib/src/interfaces/apb.dart
lib/src/interfaces/axi4.dart
lib/src/interfaces/spi.dart
lib/src/memory/csr/csr_backdoor.dart
lib/src/memory/memory.dart
lib/src/summation/sum_interface.dart
test/clock_gating_test.dart

Fix deprecated Port call to Logic.port
None
Ran dart test
No.
No change needed.

fix just the deprecated Port calls to Logic.port

---

lib/src/arithmetic/floating_point/floating_point_adder_dualpath.dart
lib/src/arithmetic/floating_point/floating_point_adder_singlepath.dart
test/arithmetic/floating_point/floating_point_adder_dualpath_test.dart
test/arithmetic/floating_point/floating_point_adder_singlepath_test.dart

Fixed a bug in the FloatingPoint Adders regarding DAZ of negative subnormals being converted to zero, but sign treated as 1.
Fix #238.
Improved tests to sweep signs on both operands and added DAZ/FTZ tests for FloatingPointSinglePathAdder as well.
No.
No.

bug in DAZ computing effectiveSubtraction incorrectly

---

example/clock_gating_example.dart
lib/src/arithmetic/divider.dart
lib/src/arithmetic/multiplier_components/partial_product_generator.dart
lib/src/clock_gating.dart
lib/src/gaskets/spi/spi_main.dart
lib/src/gaskets/spi/spi_sub.dart
lib/src/interfaces/apb.dart
lib/src/interfaces/axi4.dart
lib/src/interfaces/spi.dart
lib/src/memory/csr/csr_backdoor.dart
lib/src/memory/memory.dart
lib/src/summation/gated_counter.dart
lib/src/summation/sum_interface.dart
lib/src/summation/summation_base.dart
lib/src/toggle_gate.dart
test/apb_test.dart
test/axi4_test.dart
test/clock_gating_test.dart
test/spi/spi_bfm_test.dart
test/spi/spi_test.dart

Updated our interface classes in use in ROHD-HCL to deprecate any former static clone routines and add in the 
clone() overrides on instance classes that inherit from Interface.
None
Ran dart test.
No
Not required.

update Interface classes to include the required clone() method.
